# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7a02f1f85b7a2e2bdd9763ba53e584c66f2b49fd70122674574fe4877ee7aa2adcf1e887cee4a5414d200a491399727fbe93b6cdd0c472f56b32c4217576cc

test:
  secret_key_base: 37dd46acb7135281cd3fd614b7d45b0a01f60b9144d239c2362cb8e3792073a17a3acc168856c22e060b64621ba97f1ffae6a7c8891fc15eb579b67f674fffb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
